#Header section
- name: This plyabookis to execute the debug module and when conditions
  hosts: webservers
  vars:
    information: ['ansible_memtotal_mb','ansible_memtotal_mb.block_size','ansible_nodename','ansible_processor','ansible_product_version','ansible_hostname','ansible_architecture','ansible_architecture.BOOT_IMAGE']
# Task section
  tasks:
    - name: This task is to chcek the debug condition
      debug:
        var: "{{item}}"
      with_items: "{{information}}"
    - name: This task is to copy a file from tmp to home location
      copy:
        src: /tmp/ansiblefacts.txt
        dest: /opt/fromansible
        owner: root
        mode: 0744
